services:
  backend:
    container_name: scd_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "3000:3000"
    networks:
      - scd_private_net

  mongo:
    container_name: scd_mongo
    image: mongo:6.0
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: secret123
       MONGO_INITDB_DATABASE: testdb
    networks:
      - scd_private_net
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

networks:
  scd_private_net:
    driver: bridge

volumes:
  mongo_data:
